export default {
    
    STUDENT_DISCOUNT_RESET_REDUCER: 'STUDENT_DISCOUNT_RESET_REDUCER',
    STUDENT_DISCOUNTS_LOAD: 'STUDENT_DISCOUNTS_LOAD',
    STUDENT_DISCOUNTS_FETCHED: 'STUDENT_DISCOUNTS_FETCHED',
    STUDENT_DISCOUNTS_SCHOLARSHIP_FETCHED: 'STUDENT_DISCOUNTS_SCHOLARSHIP_FETCHED',
    STUDENT_DISCOUNTS_PARAMS: 'STUDENT_DISCOUNTS_PARAMS',
    STUDENT_DISCOUNTS_INPUT_VALUE: 'STUDENT_DISCOUNTS_INPUT_VALUE',
    STUDENT_DISCOUNTS_GET_PROFIT: 'STUDENT_DISCOUNTS_GET_PROFIT',
    
}