export default {
    
    STUDENT_DISCOUNTS_LOAD: 'STUDENT_DISCOUNTS_LOAD',
    STUDENT_DISCOUNTS_FETCHED: 'STUDENT_DISCOUNTS_FETCHED',
    STUDENT_DISCOUNTS_SCHOLARSHIP_FETCHED: 'STUDENT_DISCOUNTS_SCHOLARSHIP_FETCHED',
    STUDENT_DISCOUNTS_SET_FORM: 'STUDENT_DISCOUNTS_SET_FORM',
    STUDENT_DISCOUNTS_GET_PROFIT: 'STUDENT_DISCOUNTS_GET_PROFIT',
    
}