export default {

    ROLE_USERS_FETCHED: 'ROLE_USERS_FETCHED',
    ROLE_USERS_DETAIL: 'ROLE_USERS_DETAIL',
    ROLE_USERS_CREATED: 'ROLE_USERS_CREATED',
    ROLE_USERS_EDITED: 'ROLE_USERS_EDITED',
    ROLE_USERS_DELETED: 'ROLE_USERS_DELETED',
    ROLE_USERS_LOAD: 'ROLE_USERS_LOAD',
    // USERS_FETCHED: 'USERS_FETCHED', //desenvolver 
    // USERS_LOAD: 'USERS_LOAD', //desenvolver 
    // ROLES_LOAD: 'ROLES_LOAD',
    // ROLES_FETCHED: 'ROLES_FETCHED'

}