export default {
    
    PERMISSION_ROLES_FETCHED: 'PERMISSION_ROLES_FETCHED',
    PERMISSION_ROLES_DETAIL: 'PERMISSION_ROLES_DETAIL',
    PERMISSION_ROLES_CREATED: 'PERMISSION_ROLES_CREATED',
    PERMISSION_ROLES_EDITED: 'PERMISSION_ROLES_EDITED',
    PERMISSION_ROLES_DELETED: 'PERMISSION_ROLES_DELETED',
    PERMISSION_ROLES_LOAD: 'PERMISSION_ROLES_LOAD',
    ROLES_FETCHED: 'ROLES_FETCHED',
    ROLES_LOAD: 'ROLES_LOAD',
    PERMISSIONS_LOAD: 'PERMISSIONS_LOAD',
    PERMISSIONS_FETCHED: 'PERMISSIONS_FETCHED'
 
}