export default {
    
    ROLES_FETCHED: 'ROLES_FETCHED',
    ROLES_DETAIL: 'ROLES_DETAIL',
    ROLES_CREATED: 'ROLES_CREATED',
    ROLES_EDITED: 'ROLES_EDITED',
    ROLES_DELETED: 'ROLES_DELETED',
    ROLES_LOAD: 'ROLES_LOAD',
    
}