export default {
    ESTABLISHMENT_FETCHED: 'ESTABLISHMENT_FETCHED',
    ESTABLISHMENT_LOAD : 'ESTABLISHMENT_LOAD',
    ESTABLISHMENT_SAVE : 'ESTABLISHMENT_SAVE',
    ESTABLISHMENT_DISCARD : 'ESTABLISHMENT_DISCARD',
    ESTABLISHMENT_COURSE_FETCHED : 'ESTABLISHMENT_COURSE_FETCHED',
    ESTABLISHMENT_PERIOD_FETCHED : 'ESTABLISHMENT_PERIOD_FETCHED',
    ESTABLISHMENT_USERS_SHOW: ' ESTABLISHMENT_USERS_SHOW',
    BRANCH_USERS_SHOW: 'BRANCH_USERS_SHOW'
}
