export default {
    ESTABLISHMENT_LOAD : 'ESTABLISHMENT_LOAD',
    ESTABLISHMENT_USER: ' ESTABLISHMENT_USER',
    ESTABLISHMENT_BRANCH_USER: 'ESTABLISHMENT_BRANCH_USER',
    ESTABLISHMENT_PERIOD : 'ESTABLISHMENT_PERIOD',
    ESTABLISHMENT_SAVE : 'ESTABLISHMENT_SAVE',
    ESTABLISHMENT_DISCARD : 'ESTABLISHMENT_DISCARD',
    ESTABLISHMENT_COURSE_FETCHED : 'ESTABLISHMENT_COURSE_FETCHED',
    ESTABLISHMENT_COURSE_TYPE: 'ESTABLISHMENT_COURSE_TYPE',
}
